[project]
name = "dash-plotly-ssbg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash==2.14.2",
    "dash-bootstrap-components==1.5.0",
    "gunicorn==21.2.0",
    "pandas==2.1.4",
    "plotly==5.18.0",
]
